// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOjoZTrReAIvfW1MJ6O9qlJvMwqzrjaSc',
    appId: '1:277710406862:web:72227c54f891311037bc9f',
    messagingSenderId: '277710406862',
    projectId: 'clibo-ai',
    authDomain: 'clibo-ai.firebaseapp.com',
    storageBucket: 'clibo-ai.firebasestorage.app',
    measurementId: 'G-HWLVRMB7T2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfLq7hbHZQuvd8RTPegBn1K0L2XyKTjXg',
    appId: '1:277710406862:android:bef8de1d9b68a24337bc9f',
    messagingSenderId: '277710406862',
    projectId: 'clibo-ai',
    storageBucket: 'clibo-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcy7G-mvnw4lmGXHA6q2TI2pRSFQ3neI8',
    appId: '1:277710406862:ios:6aa67ca2f50fcf2137bc9f',
    messagingSenderId: '277710406862',
    projectId: 'clibo-ai',
    storageBucket: 'clibo-ai.firebasestorage.app',
    androidClientId: '277710406862-m9kf0s96pq1t5dabdes4nsbr1hhd2j5g.apps.googleusercontent.com',
    iosBundleId: 'com.example.clibofe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcy7G-mvnw4lmGXHA6q2TI2pRSFQ3neI8',
    appId: '1:277710406862:ios:6aa67ca2f50fcf2137bc9f',
    messagingSenderId: '277710406862',
    projectId: 'clibo-ai',
    storageBucket: 'clibo-ai.firebasestorage.app',
    androidClientId: '277710406862-m9kf0s96pq1t5dabdes4nsbr1hhd2j5g.apps.googleusercontent.com',
    iosBundleId: 'com.example.clibofe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOjoZTrReAIvfW1MJ6O9qlJvMwqzrjaSc',
    appId: '1:277710406862:web:126d6d6b7cbd142d37bc9f',
    messagingSenderId: '277710406862',
    projectId: 'clibo-ai',
    authDomain: 'clibo-ai.firebaseapp.com',
    storageBucket: 'clibo-ai.firebasestorage.app',
    measurementId: 'G-DPZRCSLSNM',
  );
}
